//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// StructureModel.rc에서 사용되고 있습니다.
//

#define MESSAGE_CMO_IDX							10000
#define MESSAGE_CMO_GEN_IDX						MESSAGE_CMO_IDX
#define MESSAGE_CMO_GEN_SLAB_PROFILE			MESSAGE_CMO_GEN_IDX
#define MESSAGE_CMO_GEN_SLAB_DIST				MESSAGE_CMO_GEN_IDX+1
#define MESSAGE_CMO_GEN_LINEMEMBEROUTLEN		MESSAGE_CMO_GEN_IDX+2
#define MESSAGE_CMO_GEN_SLAB_AREA				MESSAGE_CMO_GEN_IDX+3

#define MESSAGE_CMO_MODEL_IDX					MESSAGE_CMO_IDX+100
#define MESSAGE_CMO_MODEL_NONAME				MESSAGE_CMO_MODEL_IDX
#define MESSAGE_CMO_MODEL_VER_ZLEVELOVERLAP		MESSAGE_CMO_MODEL_IDX+1
#define MESSAGE_CMO_MODEL_HOR_ZLEVELOVERLAP		MESSAGE_CMO_MODEL_IDX+2
#define MESSAGE_CMO_MODEL_VER_CANTIL			MESSAGE_CMO_MODEL_IDX+3
#define MESSAGE_CMO_MODEL_HOR_CANTIL			MESSAGE_CMO_MODEL_IDX+4
#define MESSAGE_CMO_MODEL_NOT_CONNECTION		MESSAGE_CMO_MODEL_IDX+5
#define MESSAGE_CMO_MODEL_VER_CONTAIN			MESSAGE_CMO_MODEL_IDX+6
#define MESSAGE_CMO_MODEL_SAMEMEMBER_OVERLAP	MESSAGE_CMO_MODEL_IDX+7

#define MESSAGE_CMO_VER_SEC_IDX					MESSAGE_CMO_IDX+200
#define MESSAGE_CMO_VER_SEC_SIZE_BELOW			MESSAGE_CMO_VER_SEC_IDX
#define MESSAGE_CMO_VER_SEC_SIZE_OVER			MESSAGE_CMO_VER_SEC_IDX+1

#define MESSAGE_CMO_VER_OUTECC_IDX				MESSAGE_CMO_IDX+300
#define MESSAGE_CMO_VER_OUTECC_BELOW			MESSAGE_CMO_VER_OUTECC_IDX
#define MESSAGE_CMO_VER_OUTECC_OVER				MESSAGE_CMO_VER_OUTECC_IDX+1

#define MESSAGE_CMO_VER_SUPPORT_IDX				MESSAGE_CMO_IDX+400
#define MESSAGE_CMO_VER_SUPPORT_BELOW			MESSAGE_CMO_VER_SUPPORT_IDX
#define MESSAGE_CMO_VER_SUPPORT_OVER			MESSAGE_CMO_VER_SUPPORT_IDX+1

#define MESSAGE_CMO_HOR_SEC_IDX					MESSAGE_CMO_IDX+500
#define MESSAGE_CMO_HOR_SEC_BEAM_WIDTH_BELOW	MESSAGE_CMO_HOR_SEC_IDX
#define MESSAGE_CMO_HOR_SEC_BEAM_WIDTH_OVER		MESSAGE_CMO_HOR_SEC_IDX+1
#define MESSAGE_CMO_HOR_SEC_BEAM_HEIGHT_BELOW	MESSAGE_CMO_HOR_SEC_IDX+2
#define MESSAGE_CMO_HOR_SEC_BEAM_HEIGHT_OVER	MESSAGE_CMO_HOR_SEC_IDX+3
#define MESSAGE_CMO_HOR_SEC_SLAB_THICK_BELOW	MESSAGE_CMO_HOR_SEC_IDX+4
#define MESSAGE_CMO_HOR_SEC_SLAB_THICK_OVER		MESSAGE_CMO_HOR_SEC_IDX+5

#define MESSAGE_CMO_HOR_LEVELDIF_IDX			MESSAGE_CMO_IDX+600
#define MESSAGE_CMO_HOR_LEVELDIF_BELOW			MESSAGE_CMO_HOR_LEVELDIF_IDX
#define MESSAGE_CMO_HOR_LEVELDIF_OVER			MESSAGE_CMO_HOR_LEVELDIF_IDX+1

#define MESSAGE_CMO_UNKNOWN						65535
// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
