#ifndef __SCFMCPENUM_SCFMCPENUM_H
#define __SCFMCPENUM_SCFMCPENUM_H


#define UAV_JOINT_INS		11000
#define UAV_JOINT_EDT		11001
#define UAV_JOINT_DEL		11002

#define UAV_COMPOM_INS	11003
#define UAV_COMPOM_EDT	11004
#define UAV_COMPOM_DEL	11005

#define UAV_COMPOG_INS	11006
#define UAV_COMPOG_EDT	11007
#define UAV_COMPOG_DEL	11008

#define UAV_MACRO_CMD		11009

#define UAV_UNDO				11010
#define UAV_REDO				11011
#define UAV_COPYPLAN		11012
#define UAV_REDRAW			11013

#define SD30	0
#define SD40	1
#define SD50	2
#define SD60  3

#define STR_SD30	_T("SD30")
#define STR_SD40	_T("SD40")
#define STR_SD50	_T("SD50")
#define STR_SD60	_T("SD60")

#define STR_SD300		_T("SD300")
#define STR_SD350		_T("SD350")
#define STR_SD400		_T("SD400")
#define STR_SD400S		_T("SD400S")
#define STR_SD400W	_T("SD400W")
#define STR_SD500		_T("SD500")
#define STR_SD500S		_T("SD500S")
#define STR_SD500W	_T("SD500W")
#define STR_SD600		_T("SD600")
#define STR_SD600S		_T("SD600S")
#define STR_SD700		_T("SD700")

// for India
#define STR_Fe415		_T("Fe415")
#define STR_Fe415D	_T("Fe415D")
#define STR_Fe500		_T("Fe500")
#define STR_Fe500D	_T("Fe500D")
#define STR_Fe550		_T("Fe550")
#define STR_Fe550D	_T("Fe550D")
#define STR_Fe600		_T("Fe600")
#define STR_CRS		_T("CRS")

// for Singapore
#define STR_B485B	_T("B485B")
#define STR_B500B	_T("B500B")
#define STR_B600A	_T("B600A")
#define STR_B600B	_T("B600B")

// for GB
#define STR_HPB235		_T("HPB235")
#define STR_HPB300		_T("HPB300")
#define STR_HRB335		_T("HRB335")
#define STR_HRBF335	_T("HRBF335")
#define STR_HRB400		_T("HRB400")
#define STR_HRBF400	_T("HRBF400")
#define STR_RRB400		_T("RRB400")
#define STR_HRB500		_T("HRB500")
#define STR_HRBF500	_T("HRBF500")

// for JIS
#define STR_SD295		_T("SD295")
#define STR_SD345		_T("SD345")
#define STR_SD390		_T("SD390")
#define STR_SD490		_T("SD490")


#define BARTYPE_D		0
#define BARTYPE_HD	1
#define BARTYPE_SHD	2
#define BARTYPE_TD	3

#define STR_BARTYPE_D		_T("D")
#define STR_BARTYPE_HD	_T("HD")
#define STR_BARTYPE_SHD	_T("SHD")
#define STR_BARTYPE_UHD	_T("UHD")
#define STR_BARTYPE_TD	_T("TD")

#define ERROR_LEVEL			-1
#define WARNING_LEVEL	1


#define DefHitDist 10
#define USED_BY_STORY _T("By Story")
#define USED_STORY_MATERIAL 	_T("By Story")
#define USED_OWNER_MATERIAL 	_T("By Owner")
#define ERROR_STEEL_SECTION_FILE _T("Deleted steel sections are replaced with the default section!")

#define _BENT_OFFSET 200

// T_BarLoc 때문에 사용함.. 추후에 위치 이동 고려..
#include "GMLib/GM2DVector.h"

enum msSteelCode { 
	STEEL_CODE_KOREAN = 0,
	};

enum msSteelSecType {
	SECTION_H_TYPE	 = 0,
	SECTION_RECT_TYPE,
	SECTION_ROUND_TYPE,
	SECTION_T_TYPE,
	SECTION_C_TYPE,
	SECTION_DANGLE_TYPE,
	SECTION_ANGLE_TYPE,
	SECTION_DECK_TYPE,
};
enum msBarSetType {	// 부재당 100단위
	BEAM_TOP = 1,
	BEAM_BOT,
	BEAM_SIDE,
	BEAM_STRP_L,
	BEAM_STRP_M,
	BEAM_STRP_R,
	BEAM_STRP_COVER_L,
	BEAM_STRP_COVER_M,
	BEAM_STRP_COVER_R,
	BEAM_STRP_HOOK_L,
	BEAM_STRP_HOOK_M,
	BEAM_STRP_HOOK_R,
	BEAM_TOP_2LAYER,
	BEAM_BOT_2LAYER,
	BEAM_STRP_SUB_TOP,
	BEAM_STRP_SUB_BOT,
	BEAM_SUBMAIN,
	BEAMBUILTUP_STRP= 30,
	BEAMBUILTUP_TOP,
	BEAMBUILTUP_BOT,
	BEAM_SUBSTRP_SUPPORT,
	BEAMBUILTUP_SIDE,
	BEAM_HOR_SHEAR,
	BEAM_SHEARFRICTIONBAR,
	BEAM_DIAGONAL_ADD,
	BEAM_DIAGONAL_STRP,
	BEAM_SIDE_PRESSURE_BAR,
	BEAM_HOR_ADD_BAR,

	COLUMN_MAIN = 101,
	COLUMN_HOOP,
	COLUMN_TIE,
	COLUMN_DOWEL,
	COLUMN_DOWEL_SUPPORT,
	COLUMN_DOWEL_HOOP,
	COLUMN_HEADER_MAIN,
	COLUMN_HEADER_STIRRUP,
	COLUMN_HEADER_ADD,
	COLUMN_SUBMAIN,
	COLUMN_HOR_SHEAR,

	// Basic barset Type
	COLUMN_MAIN_TOP,
	COLUMN_MAIN_BOTTOM,
	COLUMN_MAIN_LEFT,
	COLUMN_MAIN_RIGHT,

	COLUMN_HOOP_END_BOTTOM,
	COLUMN_HOOP_MID,
	COLUMN_HOOP_END_TOP,
	COLUMN_HOOP_TOP_DEDUCTION_THICK,

	COLUMN_TIE_END_BOTTOM,
	COLUMN_TIE_MID,
	COLUMN_TIE_END_TOP,
	//COLUMN_TIE_YDIR_END_BOTTOM,
	//COLUMN_TIE_YDIR_MID,	
	//COLUMN_TIE_YDIR_END_TOP,

	COLUMN_DOWEL_TOP,
	COLUMN_DOWEL_BOTTOM,
	COLUMN_DOWEL_LEFT,
	COLUMN_DOWEL_RIGHT,
	
	COLUMN_TIE_TOP_DEDUCTION_THICK,

	SLAB_TOPLX = 201,
	SLAB_TOPLY ,
	SLAB_BOTLX ,
	SLAB_BOTLY ,
	SLAB_SPACER,
	SLAB_TOPLXADD,
	SLAB_TOPLYADD,
	SLAB_BOTLXADD,
	SLAB_BOTLYADD,
	SLAB_TOPLXENDMAIN,//SLAB_TOPLXEND,
	SLAB_TOPLXENDCUT,//SLAB_TOPLXEND2,
	SLAB_TOPLXENDBENT,//SLAB_TOPLXEND3,
	SLAB_TOPLYENDMAIN,//SLAB_TOPLYEND,
	SLAB_TOPLYENDCUT,//SLAB_TOPLYEND2,
	SLAB_TOPLYENDBENT,//SLAB_TOPLYEND3,
	SLAB_BOTLXENDMAIN,//SLAB_BOTLXEND,
	SLAB_BOTLXENDCUT,//SLAB_BOTLXEND2,
	SLAB_BOTLYENDMAIN,//SLAB_BOTLYEND,
	SLAB_BOTLYENDCUT,//SLAB_BOTLYEND2,
	SLAB_TOPLXCENMAIN, //SLAB_TOPLXCEN,
	SLAB_TOPLXCENCUT,//SLAB_TOPLXCEN2,
	SLAB_TOPLXCENBENT,//SLAB_TOPLXCEN3,
	SLAB_TOPLYCENMAIN,//SLAB_TOPLYCEN,
	SLAB_TOPLYCENCUT,//SLAB_TOPLYCEN2,
	SLAB_TOPLYCENBENT,//SLAB_TOPLYCEN3,
	SLAB_BOTLXCENMAIN,//SLAB_BOTLXCEN,
	SLAB_BOTLXCENCUT,//SLAB_BOTLXCEN2,
	SLAB_BOTLYCENMAIN,//SLAB_BOTLYCEN,
	SLAB_BOTLYCENCUT, //SLAB_BOTLYCEN2,
	SLAB_OPENINGADDBAR = 230,
	SLAB_SHEAR,
	SLAB_TOPLXCENADD = 250,
	SLAB_TOPLYCENADD,
	SLAB_TOPLXENDADD,
	SLAB_TOPLYENDADD,
	SLAB_TOPLXENDADD2,
	SLAB_TOPLYENDADD2,
	SLAB_BOTLXENDADD,
	SLAB_BOTLYENDADD,
	SLAB_TOPLXSPLICE,
	SLAB_BOTLXSPLICE,
	SLAB_TOPLYSPLICE,
	SLAB_BOTLYSPLICE,
	SLAB_BOTSPACER,
	SLAB_SPACERSUPPORTBAR,
	SLAB_SUPPORTBAR,

	DECK_BOTLXMAIN = 270,
	
	//[Q24-397] 철근 명칭 추가 - Start
	DECK_TOPLYENDMAIN = 271,
	DECK_TOPLYCENMAIN,
	DECK_BOTLYENDMAIN,
	DECK_BOTLYCENMAIN,
	DECK_BOTLXADD = 275,
	//[Q24-397] 철근 명칭 추가 - End

	PC_TOP_LX_CEN_SPLICE = 280,
	PC_TOP_LX_END_SPLICE,

	PC_BOT_LX_IN_END_SPLICE,
	PC_BOT_LX_SPLICE_END_SPLICE,
	PC_BOT_LY_CEN_SPLICE,
	PC_BOT_LY_END_SPLICE,
	
	SLAB_HOR_SUPPORTBAR,

	DECK_GENERAL_TOP_LX_SPLICE,
	DECK_GENERAL_BOT_LX_SPLICE,	
			
	PC_HCS_BOTLXADD,
	PC_HCS_BOTLXADD2,//HCS Lx 3번철근 2개일경우

	SLAB_SHEARFRICTIONBAR,

	SLAB_LX_CRACK_PREVENTION_SHEARBAR = 292,
	SLAB_LY_CRACK_PREVENTION_SHEARBAR,

	//[Q24-397] 철근 명칭 추가 - Start
	DECK_GENERAL_TOPLXCENMAIN,
	DECK_GENERAL_TOPLYCENMAIN,
	DECK_GENERAL_BOTLXCENMAIN,
	DECK_GENERAL_BOTLYCENMAIN,
	DECK_GENERAL_TOPLXADD,
	PC_RPS_BOTLXSPLICE = 299,
	//[Q24-397] 철근 명칭 추가 - End

	WALL_HORLEFT = 301,
	WALL_HORRIGHT,
	WALL_IN_HORSTART,
	WALL_IN_HORMID,
	WALL_IN_HOREND,
	WALL_OUT_HORSTART,
	WALL_OUT_HORMID,
	WALL_OUT_HOREND,
	WALL_VERLEFT,
	WALL_VERRIGHT,
	WALL_DOWELVERLEFT,
	WALL_DOWELVERRIGHT,
	WALL_DOWELHORLEFT,
	WALL_DOWELHORRIGHT,
	WALL_SPACER,
	WALL_DOWELSPACER,
	WALL_UBAR,
	WALL_CROSSBAR,
	WALL_DOWELCROSSBAR,
	WALL_INDOWELVERADDBAR,
	WALL_OUTDOWELVERADDBAR,
	WALL_INBOTVERADDBAR,
	WALL_OUTBOTVERADDBAR,
	WALL_INMIDVERADDBAR,
	WALL_OUTMIDVERADDBAR,
	WALL_INTOPVERADDBAR,
	WALL_OUTTOPVERADDBAR,
	WALL_SHEARTOPADDBAR,
	WALL_SHEARBOTADDBAR,
	WALL_ENDADDBAR,
	WALL_DOWELENDADDBAR,
	WALL_OPENINGADDBAR,
	WALL_SHEARSTARTADDBAR,
	WALL_SHEARENDADDBAR,
	WALL_OUTVERBAR,
	WALL_INVERBAR,
	WALL_SUPPORTBAR,
	WALL_ADDBAR,	
	WALL_BRACE_SUPPORTBAR,

	WALL_SPECIAL_SHEAR_VER_ADDBAR,
	WALL_SPECIAL_SHEAR_DOWEL_ADDBAR,
	WALL_SPECIAL_SHEAR_HOOP,
	WALL_SPECIAL_SHEAR_LX_TIE,
	WALL_SPECIAL_SHEAR_LY_TIE,

	WALLFOOT_LONGBOTBAR = 401,
	WALLFOOT_SHORTBOTBAR,
	WALLFOOT_SPACER,
	WALLFOOT_LONGTOPBAR,
	WALLFOOT_SHORTTOPBAR,
	WALLFOOT_BOTSPACER,
	WALLFOOT_SPACERSUPPORTBAR,
	WALLFOOT_SUPPORTBAR,

	ISOFOOT_LONGBOTBAR = 501,
	ISOFOOT_SHORTBOTBAR,
	ISOFOOT_SPACER,
	ISOFOOT_LONGTOPBAR,
	ISOFOOT_SHORTTOPBAR,
	ISOFOOT_BOTSPACER,
	ISOFOOT_SPACERSUPPORTBAR,
	ISOFOOT_SUPPORTBAR,

	PIT_TOPLXBAR = 601,
	PIT_BOTLXBAR,
	PIT_TOPLYBAR,
	PIT_BOTLYBAR,
	PIT_OUTVERBAR,
	PIT_OUTHORBAR,
	PIT_INVERBAR,
	PIT_INHORBAR,
	PIT_INNERLXADD,
	PIT_INNERLYADD,
	PIT_SPACER,
	PIT_BOTSPACER,
	PIT_SPACERSUPPORTBAR,
	PIT_SUPPORTBAR,
	PIT_WELL_ADDBAR,
	PIT_WALL_SPACER,
	PIT_BRACE_SUPPORTBAR,

	LEVELDIF_HORIN = 701,
	LEVELDIF_HOROUT,
	LEVELDIF_VERIN,
	LEVELDIF_VEROUT,
	STAIR_LANDING_TOPLX = 800,//LandingTopLx
	STAIR_LANDING_BOTLX,//LandingBotLx
	STAIR_LANDING_TOPLY,//LandingTopLy
	STAIR_LANDING_BOTLY,//LandingBotLy
	STAIR_STEP_TOPLX,//StepTopLx
	STAIR_STEP_BOTLX,//StepBotLx
	STAIR_STEP_TOPLY,//StepTopLy
	STAIR_STEP_BOTLY,//StepBotLy
	STAIR_TOPLANDTOPLYBAR_FIRST,
	STAIR_TOPLANDBOTLYBAR_FIRST,
	STAIR_TOPLANDTOPLYBAR_LAST,
	STAIR_TOPLANDBOTLYBAR_LAST,
	STAIR_FIRSTSTAIRTOPLX,
	STAIR_FIRSTSTAIRTOPLY,
	STAIR_FIRSTSTAIRBOTLX,
	STAIR_FIRSTSTAIRBOTLY,
	STAIR_LASTSTAIRTOPLX,
	STAIR_LASTSTAIRTOPLY,
	STAIR_LASTSTAIRBOTLX,
	STAIR_LASTSTAIRBOTLY,
	STAIR_BOTADDBAR,
	STAIR_TOPADDBAR,
	HANDRAIL_HORBAR=900,
	HANDRAIL_VERBAR,
	HANDRAIL_UBAR,
	HANDRAIL_HORTOPADDBAR,
	HANDRAIL_HORBOTADDBAR,
	HANDRAIL_STRPBAR,
	HANDRAIL_CAPUBAR,
	HANDRAIL_HORMIDADDBAR,
	HANDRAIL_ADDBAR,
	HANDRAIL_SUPPORTBAR,
	USER_ADDBAR = 999,
	USER_TOPLXADD = 1000,
	USER_TOPLYADD,
	USER_BOTLXADD,
	USER_BOTLYADD,
	USER_SHEARADD,
	USER_BENTLXADD,
	USER_BENTLYADD,
	USER_TOPLXMATERIALLIFT,
	USER_TOPLYMATERIALLIFT,
	USER_BOTLXMATERIALLIFT,
	USER_BOTLYMATERIALLIFT,
	USER_SHEARMATERIALLIFT,
	USER_BENTLXMATERIALLIFT,
	USER_BENTLYMATERIALLIFT,
	USER_TOPLXEVFALLPREVENTION,
	USER_TOPLYEVFALLPREVENTION,
	USER_BOTLXEVFALLPREVENTION,
	USER_BOTLYEVFALLPREVENTION,
	USER_SHEAREVFALLPREVENTION,
	USER_BENTLXEVFALLPREVENTION,
	USER_BENTLYEVFALLPREVENTION,
	
	//[Q24-397] 철근 명칭 추가 - Start
	USER_MAIN_TOPLXADD,
	USER_MAIN_TOPLYADD,
	USER_MAIN_BOTLXADD,
	USER_MAIN_BOTLYADD,
	//[Q24-397] 철근 명칭 추가 - End

	TRANSFER_SLAB_END_VER_ADD_BAR = 1201,
	TRANSFER_SLAB_END_HOR_ADD_BAR,
};

#define MESSAGE_LEVEL_INFO		0
#define MESSAGE_LEVEL_WARNING	1
#define MESSAGE_LEVEL_ERROR		-1

// enum MESSAGE_INFO {
// 
// };

enum MESSAGE_WARNING {
	MESSAGE_WARNING_MIDNODE	= 20000,
	MESSAGE_WARNING_LEVELDIF, 
	MESSAGE_WARNING_POLYLINESEFMENTDIST,
	MESSAGE_WARNING_LINMEMBERLEN,
	MESSAGE_WARNING_WALLOPENINGLOC,
	MESSAGE_WARNING_CHANGED_DEFAULT_STEEL_SECTION, 
	MESSAGE_WARNING_UNKNOWN
};

enum MESSAGE_ERROR{
	MESSAGE_ERROR_OVERLAP	= 10000,
	MESSAGE_ERROR_CONNECTED,
	MESSAGE_ERROR_SUPPORT_COLUMN,
	MESSAGE_ERROR_SUPPORT_WALL,
	MESSAGE_ERROR_CANTILEVER,
	MESSAGE_ERROR_SUPPORT_ISOFOOT,
	MESSAGE_ERROR_SUPPORT_WALLFOOT,
	MESSAGE_ERROR_SUPPORT_HANDRAIL,
	MESSAGE_ERROR_SLAB_PROFILE,
	MESSAGE_ERROR_JOINT,
	MESSAGE_ERROR_COLUMN_ECC,
	MESSAGE_ERROR_WALL_ECC,
	MESSAGE_ERROR_COLUMN_BIGCOMPOM,
	MESSAGE_ERROR_WALL_BIGCOMPOM,

	MESSAGE_ERROR_CONNECTED_BEAM_ZLEVEL,
	MESSAGE_ERROR_CONNECTED_BEAM_DEPTH,
	MESSAGE_ERROR_CONNECTED_BEAM_WIDTH,
	MESSAGE_ERROR_DEFNAME,

	MESSAGE_ERROR_COMPOM,
	MESSAGE_ERROR_POLYLINESEFMENTDIST,

	MESSAGE_ERROR_COMPOG_DEPTH_OVER,

	MESSAGE_ERROR_UNKNOWN,
	MESSAGE_ERROR_INPUT,
};

// enum MESSAGE_CMO_CODE
// {
// 	MESSAGE_CMO_IDX							= 10000,
// 
// 	MESSAGE_CMO_GEN_IDX						= MESSAGE_CMO_IDX + 0,
// 	MESSAGE_CMO_GEN_SLAB_PROFILE			= MESSAGE_CMO_GEN_IDX,
// 	MESSAGE_CMO_GEN_SLAB_DIST				= MESSAGE_CMO_GEN_IDX+1,
// 	MESSAGE_CMO_GEN_LINEMEMBEROUTLEN		= MESSAGE_CMO_GEN_IDX+2,
// 
// 	MESSAGE_CMO_MODEL_IDX					= MESSAGE_CMO_IDX + 100,
// 	MESSAGE_CMO_MODEL_NONAME				= MESSAGE_CMO_MODEL_IDX,
// 	MESSAGE_CMO_MODEL_VER_ZLEVELOVERLAP		= MESSAGE_CMO_MODEL_IDX+1,
// 	MESSAGE_CMO_MODEL_HOR_ZLEVELOVERLAP		= MESSAGE_CMO_MODEL_IDX+2,
// 	MESSAGE_CMO_MODEL_VER_CANTIL			= MESSAGE_CMO_MODEL_IDX+3,
// 	MESSAGE_CMO_MODEL_HOR_CANTIL			= MESSAGE_CMO_MODEL_IDX+4,
// 	MESSAGE_CMO_MODEL_NOT_CONNECTION		= MESSAGE_CMO_MODEL_IDX+5,
// 	
// 	MESSAGE_CMO_VER_SEC_IDX					= MESSAGE_CMO_IDX + 200,
// 	MESSAGE_CMO_VER_SEC_SIZE_BELOW			= MESSAGE_CMO_VER_SEC_IDX,
// 	MESSAGE_CMO_VER_SEC_SIZE_OVER			= MESSAGE_CMO_VER_SEC_IDX+1,
// 	
// 	MESSAGE_CMO_VER_OUTECC_IDX				= MESSAGE_CMO_IDX + 300,
// 	MESSAGE_CMO_VER_OUTECC_BELOW			= MESSAGE_CMO_VER_OUTECC_IDX,
// 	MESSAGE_CMO_VER_OUTECC_OVER				= MESSAGE_CMO_VER_OUTECC_IDX+1,
// 	
// 	MESSAGE_CMO_VER_SUPPORT_IDX				= MESSAGE_CMO_IDX + 400,
// 	MESSAGE_CMO_VER_SUPPORT_BELOW			= MESSAGE_CMO_VER_SUPPORT_IDX,
// 	MESSAGE_CMO_VER_SUPPORT_OVER			= MESSAGE_CMO_VER_SUPPORT_IDX+1,
// 	
// 	MESSAGE_CMO_HOR_SEC_IDX					= MESSAGE_CMO_IDX + 500,
// 	MESSAGE_CMO_HOR_SEC_BEAM_WIDTH_BELOW	= MESSAGE_CMO_HOR_SEC_IDX,
// 	MESSAGE_CMO_HOR_SEC_BEAM_WIDTH_OVER		= MESSAGE_CMO_HOR_SEC_IDX+1,
// 	MESSAGE_CMO_HOR_SEC_BEAM_HEIGHT_BELOW	= MESSAGE_CMO_HOR_SEC_IDX+2,
// 	MESSAGE_CMO_HOR_SEC_BEAM_HEIGHT_OVER	= MESSAGE_CMO_HOR_SEC_IDX+3,
// 	MESSAGE_CMO_HOR_SEC_SLAB_THICK_BELOW	= MESSAGE_CMO_HOR_SEC_IDX+4,
// 	MESSAGE_CMO_HOR_SEC_SLAB_THICK_OVER		= MESSAGE_CMO_HOR_SEC_IDX+5,
// 	
// 	MESSAGE_CMO_HOR_LEVELDIF_IDX			= MESSAGE_CMO_IDX + 600,
// 	MESSAGE_CMO_HOR_LEVELDIF_BELOW			= MESSAGE_CMO_HOR_LEVELDIF_IDX,
// 	MESSAGE_CMO_HOR_LEVELDIF_OVER			= MESSAGE_CMO_HOR_LEVELDIF_IDX+1,
// };



enum ERROR_MSG_TYPE{
	COGREADER_ERROR_NOT_FIND_COMPOG = 0
	,ADD_MEMBER_ERROR_INS_SAME_LOC = 100
};


enum eCheckModel
{
	CMO_GEN = 2,
	CMO_MODEL = 4,
	CMO_VER_SEC = 8,
	CMO_VER_OUTECC = 16,
	CMO_VER_SUPPORT = 32,
	CMO_HOR_SEC = 64,
	CMO_HOR_LEVELDIF = 128,
	CMO_BASE_CNT = 7,
};

enum eCheckModelGenOption
{
	CMO_GEN_SLAB_PROFILE = 2,
	CMO_GEN_SLAB_DIST = 4,
	CMO_GEN_LINEMEMBEROUTLEN = 8,
	CMO_GEN_SLAB_AREA = 16,
	CMO_GEN_CNT = 4,
};

enum eCheckModelModelingOption
{
	CMO_MODEL_NONAME = 2,
	CMO_MODEL_VER_ZLEVELOVERLAP = 4,
	CMO_MODEL_HOR_ZLEVELOVERLAP = 8,
	CMO_MODEL_VER_CANTIL = 16,
	CMO_MODEL_HOR_CANTIL = 32,
	CMO_MODEL_NOT_CONNECTION = 64,
	CMO_MODEL_VER_CONTAIN = 128,
	CMO_MODEL_SAMEMEMBER_OVERLAP = 256,
	CMO_MODEL_CNT = 8,
};

enum eCheckModelVerSecOption
{
	CMO_VER_SEC_SIZE_BELOW = 2,
	CMO_VER_SEC_SIZE_OVER = 4,
	CMO_VER_SEC_CNT = 2,
};

enum eCheckModelVerOutEccOption
{
	CMO_VER_OUTECC_BELOW = 2,
	CMO_VER_OUTECC_OVER = 4,
	CMO_VER_OUTECC_CNT = 2,
};

enum eCheckModelVerSupportOption
{
	CMO_VER_SUPPORT_BELOW = 2,
	CMO_VER_SUPPORT_OVER = 4,
	CMO_VER_SUPPORT_CNT = 2,
};

enum eCheckModelHorSecOption
{
	CMO_HOR_SEC_BEAM_WIDTH_BELOW = 2,
	CMO_HOR_SEC_BEAM_WIDTH_OVER = 4,
	CMO_HOR_SEC_BEAM_HEIGHT_BELOW = 8,
	CMO_HOR_SEC_BEAM_HEIGHT_OVER = 16,
	CMO_HOR_SEC_SLAB_THICK_BELOW = 32,
	CMO_HOR_SEC_SLAB_THICK_OVER = 64,
	CMO_HOR_SEC_CNT = 6,
};

enum eCheckModelHorDifOption
{
	CMO_HOR_LEVELDIF_BELOW = 2,
	CMO_HOR_LEVELDIF_OVER = 4,
	CMO_HOR_LEVELDIF_CNT = 2,
};

enum eZLevelInfo
{
	LowUrMember = 2,
	ZLevelConnection = 4,
	ZLevelOverLap = 8,
	SameTopBotZLevel = 16
};
enum Type_RebarOwnerClassification
{
    rocNone = -1,
    rocColumn,
    rocButtress,
    rocCustomColumn,
    rocBearingWall,
    rocRetainingWall,
    rocWallColumn,
    rocLowWall,
    rocLevelDiffWall,
    rocBeam,
    rocPCBeam,
    rocCustomBeam,
    rocSlab,
    rocSlabOnBeam,
    rocFoundationSlab,
    rocFlatSlab,
    rocMatSlab,
    rocFlatSlabA,
    rocFlatSlabB,
    rocSOGSlab,
    rocCircularRamp,
    rocHalfPCSlab,
    rocIMTSlab,
    rocRebarEmbeddedDeck,
    rocDeckSlab,
    rocPCSlab,
    rocDropPanel,
    rocPit,
    rocIsoFoot,
    rocWallFoot,
    rocStair,
    rocSlabAddBar,
    rocSlabAddBarMaterialLift,
    rocSlabAddBarForEvFallPrevention,
    rocSRCColumn,
    rocSRCBeam
};
/*
typedef struct _err_msg_t
{
	ERROR_MSG_TYPE idx;
	CString group;
	CString msg;
} err_msg_t;


err_msg_t err_msg_list[100] ={
	{COGREADER_ERROR_NOT_FIND_COMPOG, _T("도면인식"), _T("객체에서 부재를 생성 할수 없습니다.")}
	,{ADD_MEMBER_ERROR_INS_SAME_LOC, _T("부재추가"), _T("같은 위치에 부재가 추가 되었습니다.")}

};
*/

// MSConnection 에서 사용되는 Enum
enum CON_POS {CON_START = 0, CON_END = 1, CON_MID = 2, CON_ALL = 3, CON_UNKNOWN = -1};

enum eFIND_FLOOR {FIND_DNFLOOR = -1, FIND_CURFLOOR = 0, FIND_UPFLOOR = 1, FIND_ALLFLOOR = 2};

enum eLINEALIGN_TYPE {LINEALIGN_LEFT = -1, LINEALIGN_CENTER = 0, LINEALIGN_RIGHT = 1};

enum ePOINTALIGN_TYPE
{
	COLUMNALIGN_TOPLEFT = 1,
	COLUMNALIGN_TOP = 2,
	COLUMNALIGN_TOPRIGHT = 3,
	COLUMNALIGN_LEFT = 4,
	COLUMNALIGN_CENTER = 5,
	COLUMNALIGN_RIGHT = 6,
	COLUMNALIGN_BOTTOMLEFT = 7,
	COLUMNALIGN_BOTTOM = 8,
	COLUMNALIGN_BOTTOMRIGHT = 9
};


// 2D 철근집계표는 아래 이름에 해당되는 Layer로 설정되어 있다.
#define STR_NX_TABLE										_T("NX_TABLE")
#define STR_NX_TABLE_ELEV_PIT					_T("NX_TABLE_ELEV_PIT")
#define STR_NX_TABLE_FOUNDATION			_T("NX_TABLE_FOUNDATION")
#define STR_NX_TABLE_COLUMN					_T("NX_TABLE_COLUMN")
#define STR_NX_TABLE_COLUMN_DOWEL	_T("NX_TABLE_COLUMN_DOWEL")
#define STR_NX_TABLE_WALL							_T("NX_TABLE_WALL")
#define STR_NX_TABLE_WALL_DOWEL			_T("NX_TABLE_WALL_DOWEL")
#define STR_NX_TABLE_SLAB							_T("NX_TABLE_SLAB")
#define STR_NX_TABLE_GIRDER						_T("NX_TABLE_GIRDER")
#define STR_NX_TABLE_STAIRS						_T("NX_TABLE_STAIRS")

enum eColumnBarType {
	ColumnBarType_AllBar = 0,
	ColumnBarType_TopBar = 1,
	ColumnBarType_BotBar = 2,
	ColumnBarType_LeftBar = 3,
	ColumnBarType_RightBar = 4,
};

enum eBuildingUpdateType
{
	BuildingUpdateType_NONE = 0,
	BuildingUpdateType_ALL = 1,
	BuildingUpdateType_3DView = 2,
};

enum eRapBuildingUpdateType
{
	RapBuildingUpdateType_NONE = 0,
	RapBuildingUpdateType_ReGen_RapBarSet = 1
};

enum eVisibileCurveType
{
	VisibileCurveType_InVisibile = 0,
	VisibileCurveType_Visibile = 1,
	VisibileCurveType_Hidden = 2
};

enum FindType_MSElement
{
	msNULL = 0, msBuilding = 1, msFloor, msBeamG, msBraceG, msWallG, msColumnG, msIsoFootG, msRampG, msSlabG, msStairG, msPitG,
	msWallFootG, msProject, msSector, msBeamLine, msSlabLineG, msLineLevelDifG, msPointLevelDifG, msHandRailG, msWallJointG, msLevelZone, msOpening,
	msWindowG, msDoorG, /*msWallOpeningG,*/ msStairPart = 26, msSlabRebar, msWell, msTrench, msOpeningG, msWallOpeningExtraG, msConstructionZone, msHaunchG, msSectionView,
	msStoryMaterial,
	msBuiltUpBeam = 40, msWallColumnG, msFWSurfaceFoldingG,
	
	msFindEum = 100, 
	msPointMember = 100, msVerticalLineMember, msLinkMember, msPolyMember, msFloorPolyMember, msVerticalPolyMember, msSlabOrOpening
};

enum eCustomM_SectionType
{
	Column = 0,
	WallColumn = 1,
	Beam_Small = 2, Beam_Mid = 3, Beam_Large = 4
};

enum class eConstructionPhase 
{
	preConstruction = 0, 
	concurrentConstruction = 1
};


enum UIDType
{
	msElement = 0, msCompoM,
	xErrorObject, ropObject, msMaterial, msReinforceBar, msReinforceBarSetting, msMarkM, msCustomBarUnit, msCustomReBarLine, msCustomSection, msRibTypeM,
	msWallEndRebarLine, msWallEndRebarM, msBarSet, msRebarShape, dtStirrup, rebarTemplateManager
};


enum eSurfaceFoldingMType { Triangle = 0, PolyLine = 1 };

#endif // 
